import type { Metadata } from "next";
import { Unbounded, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { date } from "zod";

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
});

const IBMPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Diego Meza portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const year = new Date().getFullYear();
  return (
    <html lang="es">
      <body
        className={`${unbounded.variable} ${IBMPlexSans.variable} antialiased font-ibmPlex text-platinum-100 p-5 relative`}
      >
        <header className="flex justify-end md:justify-between md:w-[calc(100%-326px)] md:ml-[326px] w-full mb-5">
          <nav className="hidden md:block">
            <ul className="flex gap-5 font-unbounded text-lg">
              <li>
                {" "}
                <a href="#">Sobre mí</a>{" "}
              </li>
              <li>
                {" "}
                <a href="#">Habilidades</a>{" "}
              </li>
              <li>
                {" "}
                <a href="#">Proyectos</a>{" "}
              </li>
              <li>
                {" "}
                <a href="#">Contacto</a>{" "}
              </li>
            </ul>
          </nav>
          <button className="inline-block w-fit font-unbounded cursor-pointer text-sm">
            En | <span className="text-brand-folly">Es</span>
          </button>
        </header>
        <Sidebar />
        <main className="my-5 md:w-[calc(100%-326px)] md:ml-[326px] w-full">
          {children}
        </main>
        <footer className="md:w-[calc(100%-326px)] md:ml-[326px] bg-night-800 flex justify-center items-center text-sm font-unbounded py-5 rounded text-platinum-200 gap-2">
          <p>
            © Creado y desarrollado por{" "}
            <span className="font-bold text-brand-folly"> Diego Meza</span>,{" "}
            <time>{year}</time>
          </p>
        </footer>
      </body>
    </html>
  );
}
