import type { Metadata } from "next";
import { Unbounded, IBM_Plex_Sans } from "next/font/google";
import "../globals.css";

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
});

const IBMPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Diego Meza portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const year = new Date().getFullYear();
  return (
    <html lang="es">
      <body
        className={`${unbounded.variable} ${IBMPlexSans.variable} antialiased font-ibmPlex text-platinum-100 relative`}
      >
        <header className="flex w-full mb-5 bg-night-800 min-h-20 items-center px-5">
          <h1 className="text-3xl font-unbounded">
            <span className="text-brand-folly font-bold">Diego Meza</span>{" "}
            Portfolio
          </h1>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
