import type { Metadata } from "next";
import { Unbounded, IBM_Plex_Sans } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
});

const IBMPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Diego Meza portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  const year = new Date().getFullYear();
  return (
    <html lang={locale}>
      <body
        className={`${unbounded.variable} ${IBMPlexSans.variable} antialiased font-ibmPlex text-platinum-100 p-5 relative`}
      >
        <Header locale={locale as "es" | "en"} />
        <Sidebar location={locale as "es" | "en"} />
        <main className="my-5 md:w-[calc(100%-340px)] md:ml-[340px] w-full md:mt-20 md:mx-5 space-y-10">
          {children}
        </main>
        <footer className="md:w-[calc(100%-340px)] md:ml-[340px] bg-night-800 flex justify-center items-center text-sm font-unbounded py-5 rounded text-platinum-200 gap-2">
          <p>
            © {locale === "es" ? "Desarrollado por" : "Developed by"}{" "}
            <span className="font-bold text-brand-folly"> Diego Meza</span>,{" "}
            <time>{year}</time>
          </p>
        </footer>
      </body>
    </html>
  );
}
